#! /bin/sh


#   _
#  | |__  ___ _ ____      ___ __ ___  _ __ ___
#  | '_ \/ __| '_ \ \ /\ / / '_ ` _ \| '__/ __|
#  | |_) \__ \ |_) \ V  V /| | | | | | | | (__
#  |_.__/|___/ .__/ \_/\_/ |_| |_| |_|_|  \___|
#            |_|
#
#  made by jusplp (https://github.com/JusPLP)


# remove X cursor
xsetroot -cursor_name left_ptr

# desktop and monitor
bspc monitor -d                         

# gap and padding
bspc config window_gap             8
bspc config top_padding            66
bspc config bottom_padding         2
bspc config right_padding          2
bspc config left_padding           2

# border
bspc config border_width           4
bspc config focused_border_color   "#928374"
bspc config normal_border_color    "#7c6f64"

bspc config focus_follows_pointer  true

bspc config split_ratio            0.50
bspc config borderless_monocle     false
bspc config gapless_monocle        false


## RULES ##


# floating windows (with "xprop | grep WM_CLASS" you can see the name for the application)
bspc rule -a "Psensor" state=floating rectangle=900x550+0+0 center=true
bspc rule -a "Pavucontrol" state=floating rectangle=800x500+0+0 center=true
bspc rule -a "Viewnior" state=floating rectangle=900x600+0+0 center=true
bspc rule -a "Nitrogen" state=floating rectangle=900x600+0+0 center=true
bspc rule -a "Soundux" state=floating rectangle=900x600+0+0 center=true
bspc rule -a "VirtualBox Manager" rectangle=900x500+0+0 state=floating center=true

# if window is floating
bspc rule -a "Alacritty" rectangle=700x500+0+0 center=true
bspc rule -a "kitty" rectangle=700x500+0+0 center=true
bspc rule -a "Brave-browser" rectangle=1300x800+0+0 center=true
bspc rule -a "Spotify" rectangle=1300x800+0+0 center=true
bspc rule -a "Pcmanfm" rectangle=1000x700+0+0 center=true

# programs open automatically on the specified desktop
 # desktop 1
bspc rule -a "steam" desktop =^1 follow=true
bspc rule -a "yuzu" desktop =^1 follow=true
bspc rule -a "osu.exe" desktop =^1 follow=true
bspc rule -a "PrismLauncher" desktop =^1 follow=true
 # desktop 2
bspc rule -a "Brave-browser" desktop=^2 follow=true
 # desktop 3
bspc rule -a "VirtualBox Manager" desktop =^3 follow=true
bspc rule -a "Gimp-2.10" desktop =^3 follow=true
bspc rule -a "Code" desktop =^3 follow=true
bspc rule -a "obs" desktop =^3 follow=true
bspc rule -a "resolve" desktop =^3 follow=true
bspc rule -a "polychromatic-controller" desktop =^3 follow=true
 # desktop 4
bspc rule -a "Revolt" desktop =^4 follow=true
bspc rule -a "discord" desktop =^4 follow=true
 # desktop 5
bspc rule -a "Spotify" desktop =^5 follow=true


## LAUNCH PROGRAMS ##


# launch sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# launch wallpaper
feh --bg-fill ~/wallpaper/walls/gas2.jpg

# launch polybar
sh /home/JusPLP/.config/polybar/launch.sh

# launch clipmenud
clipmenud

# launch picom
picom
